### ISSUE TITLE
Metadata for Quicklisp

### ISSUE THREAD

**Issue by hydandata** [dochang/magicffi#3]
Please consider adding :description, :author and :license information to your ASDF system(s). This will greatly help Quicklisp users and make it easier for them to report bugs.

More information:

http://blog.quicklisp.org/2015/05/looking-for-more-metadata.html
https://www.quicklisp.org

**Comment by dochang** [comment]
`:magicffi` have these metadata.  I've checked the failure report, it's `:magicffi-test`.  Should I add these metadata for a test system?

**Comment by hydandata** [comment]
Thank you for the reply. It would be great to have all systems populated with that information, but if its too much trouble, I understand. I will likely submit pull requests for projects that have it missing only from tests.

**Comment by dochang** [comment]
OK, the metadata have been added to `:magicffi-test`.  I will close this issue.
